name: Debug publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: node --version && npm --version && node -p "require('./package.json').version"

      - run: npm publish --tag canary --loglevel verbose
